### ISSUE TITLE
Figure out a way to stop duplicate comments and prevent spam

### ISSUE THREAD

**Issue by neojp** [neojp/l4c.me#26]
http://clabie.com/freddier/a-small-town-girl-living-in-a-lonely-world-train-en-vivo#comments

**Comment by naxhh** [comment]
Maybe hard (time-consuming) but nice approachs
http://www.slideshare.net/butest/web-spam-detection-using-machine-learning-3860116
http://seclab.tuwien.ac.at/papers/acsac10-socialnets.pdf
