### ISSUE TITLE
Review and add missing Twitter cards' meta tags.

### ISSUE THREAD

**Issue by neojp** [neojp/l4c.me#46]
Some are displaying the wrong Twitter's creator ID, it's showing up as @cristalab when it should be the actual uploader's twitter information.

Also, change the current twitter:site to twitter:site:id

https://dev.twitter.com/docs/cards

**Comment by naxhh** [comment]
Any example ? I can't found one :\

**Comment by neojp** [comment]
We are using twitter cards & opengraph tags, look at the source code on single images, inside the `<head>`
http://clabie.com/freddier/foto-exclusiva-de-la-siguiente-generacion-de-project-glass-con-sergey-brin
