### ISSUE TITLE
Try GraphicsMagick as a replacement for Image Magick

### ISSUE THREAD

**Issue by neojp** [neojp/l4c.me#6]
https://github.com/aheckmann/gm

**Comment by freddier** [comment]
Leyendo, suena super interesante. Más veloz que ImageMagick siempre promete.

**Comment by freddier** [comment]
¿Necesitas que lo instale en el servidor?

**Comment by neojp** [comment]
Dejame probarlo en localhost primero, necesito asegurarme que todo funcione antes de tratar de instalarlo en el servidor.

**Comment by neojp** [comment]
Funciona muy bien en localhost, intentare instalarlo en el servidor de produccion.

**Comment by neojp** [comment]
Listo, GraphicsMagick FTW.
